### ISSUE TITLE
Defaults for username and icon are wrong.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.slack#12]
I was expecting the default for the username and icon would be the webhook settings, but instead they are the operator name and the streams logo.

I think it makes more sense for the defaults to come from the webhook, it's much easier for the admin to set them up and modify them that way.

**Comment by nelsonong** [comment]
I agree. Changed in pr https://github.com/IBMStreams/streamsx.slack/pull/16 to use WebHook config's username/icon by default.
