### ISSUE TITLE
Allow username and icon from tuple.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.slack#13]
I think instead of having a fixed username and icon the operator should have them come from input tuple attributes only. If not provided then they would come from the webhook definition, see #12 .

I have a potential use case for this useful operator where the username and icon need to come from the tuple rather than being fixed.

**Comment by nelsonong** [comment]
*username* and *iconUrl* now defined through tuple attributes (pr https://github.com/IBMStreams/streamsx.slack/pull/17).

The 3 optional params are now: *usernameAttr*, *iconUrlAttr*, and *messageAttr*.

**Comment by ddebrunner** [comment]
The new Kafka operators are using 'Attribute', e.g. 'messageAttribute'.

https://github.com/IBMStreams/streamsx.kafka/issues/17#issuecomment-307842552

**Comment by chanskw** [comment]
+1 on standardized format
+1 on using Attribute

I also think we should start documenting these guidelines somewhere so people can have a reference.

**Comment by nelsonong** [comment]
Okay, using Attribute. Merged pr https://github.com/IBMStreams/streamsx.slack/pull/17.
