### ISSUE TITLE
SlackSendMessage operator should not create threads directly.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.slack#2]
Operators should use the provided ThreadFactory otherwise the operator can be finalized while there is outstanding work.

https://github.com/IBMStreams/streamsx.slack/blob/master/com.ibm.streamsx.slack/impl/java/src/com/ibm/streamsx/slack/SendSlackMessage.java#L174

It's actually not clear why a separate thread is being used, since the process call waits for the other thread anyway.

Potentially a better mechanism would be use of the scheduled executor service, though it's a little unclear what is going on, the comments don't seem to match the code.

**Comment by ddebrunner** [comment]
The operator should consider extending the standard pattern `TupleConsumer` which probably addresses what the threading code is trying to do:

https://www.ibm.com/support/knowledgecenter/SSCRJU_3.2.1/com.ibm.swg.im.infosphere.streams.spl-java-operators.doc/samples/com/ibm/streams/operator/samples/patterns/TupleConsumer.html

**Comment by nelsonong** [comment]
Okay, I will look into using ThreadFactory, instead. That wait code in the process call should be removed.

When two slack messages are sent within 1 second of each other, Slack rejects the second message. So my goal with creating the thread was to wait 1 second, then re-attempt to send the rejected message without blocking the operator from its normal activity.

**Comment by ddebrunner** [comment]
`TupleConsumer` is probably the best way to handle that.

The operator could maintain a last time sent and then schedule a task in the future to send the next message.

**Comment by nelsonong** [comment]
I changed the operator to use TupleConsumer here: https://github.com/IBMStreams/streamsx.slack/pull/4.
