### ISSUE TITLE
Build fails with missing HTTP symbols

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.slack#5]
after a git clone I execute this:

cd com.ibm.streamsx.slack
ant

and hit the errors below.

Is there a different process for building?

```
compile:
    [javac] Compiling 1 source file to /home/streamsadmin/slack/streamsx.slack/com.ibm.streamsx.slack/impl/java/classes
    [javac] /home/streamsadmin/slack/streamsx.slack/com.ibm.streamsx.slack/impl/java/src/com/ibm/streamsx/slack/SendSlackMessage.java:15: error: package org.apache.http does not exist
    [javac] import org.apache.http.HttpResponse;
    [javac]                       ^
    [javac] /home/streamsadmin/slack/streamsx.slack/com.ibm.streamsx.slack/impl/java/src/com/ibm/streamsx/slack/SendSlackMessage.java:16: error: package org.apache.http.client does not exist
    [javac] import org.apache.http.client.HttpClient;
    [javac]                              ^

```

**Comment by nelsonong** [comment]
Can you try running "ant all" and see if that works? I think I may need to set a default target for the build

**Comment by ddebrunner** [comment]
I created PR #6  to fix this.

**Comment by ddebrunner** [comment]
`ant all` didn't work - the javac target didn't include the http jars.

**Comment by ddebrunner** [comment]
With pr #6 the build doesn't have errors, but doesn't result in a toolkit with the operator.

**Comment by ddebrunner** [comment]
Ahh, the `jar` target in build.xml does not actually create the jar, it just deletes the classes!

**Comment by nelsonong** [comment]
I referenced the elasticsearch build.xml and remade the one in slack. I just create a pr https://github.com/IBMStreams/streamsx.slack/pull/8. Can you test to see if it works on your end?

**Comment by ddebrunner** [comment]
Seems the build.xml is broken with two project roots.

**Comment by nelsonong** [comment]
Yeah my bad, should be fixed now. I updated pr https://github.com/IBMStreams/streamsx.slack/pull/8. Can you verify?

**Comment by ddebrunner** [comment]
I'll try it out  - I also added a comment to the PR, the copyright is incorrect.

**Comment by ddebrunner** [comment]
build works for me with the pr.

**Comment by ddebrunner** [comment]
got the operatror working - sending messages to a slack channel! :-)

**Comment by nelsonong** [comment]
Awesome! I fixed the copyright and merged
