### ISSUE TITLE
Documentation optional parameter defaults.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.slack#9]
Four parameters are optional but the documentation does not say what they default to.

**Comment by nelsonong** [comment]
I have edited the documentation in pr https://github.com/IBMStreams/streamsx.slack/pull/15 for all the optional parameters, except *batchSize*.
I think this one is inherited from *TupleConsumer* and I'm not sure how to edit the description for this parameter.

**Comment by ddebrunner** [comment]
I actually think the `batchSize` parameter should be hidden by this operator.

**Comment by nelsonong** [comment]
Yeah I agree, do you know how to hide it from documentation?

**Comment by nelsonong** [comment]
I don't actually specify it anywhere, spl-make-doc just generates it.

**Comment by ddebrunner** [comment]
```
public void setBatchSize(int batchSize) { }
```

**Comment by nelsonong** [comment]
Okay, I think I updated everything in pr https://github.com/IBMStreams/streamsx.slack/pull/16.
